export { Header } from "./header/Header"
export { Footer } from "./footer/Footer"
export { Hero } from "./hero/Hero"
export { SignIn } from "components/authorization/signIn/SignIn"
export { SignUp } from "components/authorization/signUp/SignUp"